name: Check linters and formatters

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install ruff
        run: pip install ruff

      - name: run ruff check
        run: ruff check .
      
      - name: run ruff format
        run: ruff format .
      
      

