name: Check linters, formatters, tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  formatters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: install ruff
        run: pip install ruff

      - name: run ruff check
        run: ruff check .
      
      - name: run ruff format
        run: ruff format .

      # - name: mypy check
      #   run: mypy .


  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: install poetry
        run: pip install poetry

      - name: install dependencies
        run: poetry install --with dev

      - name: run tests
        run: poetry run pytest

